########################################################
##                    PRIMAX CORE                      ##
##    Configuration file for the Primax Core plugin    ##
##  Adjust the settings below as per your requirements ##
########################################################

# The language file to use for plugin messages.
# Must be a valid language code from the "locale" folder.
lang: en

########################################################
##                  DO NOT CHANGE                     ##
########################################################

# Configuration file version.
# Changing this may break compatibility with the plugin.
config_version: 1